---
title: "data_analysis"
author: "jakeblum"
date: "5/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# packages #
library(tidyverse)
```

```{r}
data = read_csv("output/test2.csv")
data$id = as.factor(data$id)
data$idx = as.factor(data$idx)
data
```

```{r}
timeseries_1 = data %>% filter(id==1 | id == 2, idx==1 | idx==2, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=v,color=idx), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layers 1 and 2, neuron 1 and 2, timesteps of 10, measuring voltage
timeseries_1
ggsave("graphs/2layer_2neuron_voltage.png")

timeseries_2 = data %>% filter(id==1, idx==1 | idx==2 | idx==3, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=v,color=idx), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layer 1, neuron 1, 2, and 3, timesteps of 10, measuring voltage
timeseries_2
ggsave("graphs/1layer_3neuron_voltage.png")

timeseries_3 = data %>% filter(id==1 | id == 2, idx==1 | idx==2, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=stdp,color=idx), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layers 1 and 2, neuron 1 and 2, timesteps of 10, measuring stdp
timeseries_3
ggsave("graphs/2layer_2neuron_plasticity.png")

timeseries_4 = data %>% filter(id==1, idx==1 | idx==2 | idx==3, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=stdp,color=idx), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layer 1, neuron 1, 2, and 3, timesteps of 10, measuring stdp
timeseries_4
ggsave("graphs/1layer_3neuron_plasticity.png")

timeseries_5 = data %>% filter(idx==1, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=v,color=id), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layers all, neuron 1, timesteps of 10, measuring voltage
timeseries_5
ggsave("graphs/3layer_1neuron_voltage.png")

timeseries_6 = data %>% filter(idx==1, t %% 10 == 0) %>% ggplot(aes(x=t)) +
  geom_line(aes(y=stdp,color=id), alpha=0.5) +
  geom_line(aes(y=input_idx))

# layers all, neuron 1, timesteps of 10, measuring voltage
timeseries_6
ggsave("graphs/3layer_1neuron_plasticity.png")
```



